name : push test
on: push

jobs:
  push-job:
    name: push check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: dependency
      run: |
        python -m pip install â€“upgrade pip
        pip3 install -r requirements.txt;
    - name: Run server
      run: |
        python3 server.py > log.txt 2>&1 &
